import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI6fobX71nfAL8hSqXjBxTEY_HN2YKlm8',
    appId: '1:118289563946:android:9d9b7c1d2950f89ce45e53',
    messagingSenderId: '118289563946',
    projectId: 'fire-intro-24408',
    storageBucket: 'fire-intro-24408.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB19CPwvs_7OqF8Dzzj2Cw4kBgJAQjW1iE',
    appId: '1:118289563946:web:9514fafc8960162fe45e53',
    messagingSenderId: '118289563946',
    projectId: 'fire-intro-24408',
    authDomain: 'fire-intro-24408.firebaseapp.com',
    storageBucket: 'fire-intro-24408.firebasestorage.app',
    measurementId: 'G-M6MKXFXEPV',
  );

}